-- Jalankan SQL ini di Supabase > SQL Editor.
-- Perubahan: kuliah dan praktikum dapat memiliki hari berulang setiap minggu.

create table if not exists public.academic_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  date date not null,
  time time,
  category text not null check (category in ('kuliah','praktikum','tugas')),
  day_of_week integer,
  location text,
  note text,
  status text not null default 'belum' check (status in ('belum','selesai')),
  created_at timestamptz not null default now()
);

-- Jika tabel academic_items sudah pernah dibuat dari versi lama:
alter table public.academic_items
add column if not exists day_of_week integer;

-- Isi hari dari tanggal lama agar data lama tetap dapat digunakan.
update public.academic_items
set day_of_week =
  case
    when extract(dow from date) = 0 then 7
    else extract(dow from date)::integer
  end
where day_of_week is null
  and category in ('kuliah','praktikum');

-- Pastikan nilai hari hanya 1-7.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'academic_items_day_of_week_check'
  ) then
    alter table public.academic_items
    add constraint academic_items_day_of_week_check
    check (day_of_week is null or day_of_week between 1 and 7);
  end if;
end $$;

alter table public.academic_items enable row level security;

drop policy if exists "Users can view own academic items" on public.academic_items;
create policy "Users can view own academic items"
on public.academic_items for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own academic items" on public.academic_items;
create policy "Users can insert own academic items"
on public.academic_items for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update own academic items" on public.academic_items;
create policy "Users can update own academic items"
on public.academic_items for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own academic items" on public.academic_items;
create policy "Users can delete own academic items"
on public.academic_items for delete
using (auth.uid() = user_id);

create index if not exists academic_items_user_date_idx
on public.academic_items(user_id, date);

create index if not exists academic_items_user_day_idx
on public.academic_items(user_id, day_of_week);
